pymagicc/__init__.py
tests/test_pymagicc.py

If environment variable 'MAGICC_EXECUTABLE' is set, this binary is used run instead of the included version of magicc.

Add optional 'MAGICC_EXECUTABLE' environment parameter

---

tests/conftest.py
tests/test_pymagicc.py

These tests can be skipped by passing --no-slow to pytest. The default
is to run the slow tests

Make tests which run magicc as slow

---

pymagicc/api.py
tests/test_api.py

Delay the creation of the temporary directory until `create_copy` is
called. `run_dir` and `out_dir` now return None, until `create_copy` is
called.

Don't automatically create a temp directory on object instantiation

---

pymagicc/__init__.py
pymagicc/api.py

I won't die in a ditch whether or not to expose a MAGICC class (which defaults to MAGICC6) as the default implementation of the API.
Either way, MAGICCBase is a better name as it is an abstract base class and cannot be directly instantiated.

Rename MAGICC baseclass to MAGICCBase and expose MAGICC6 as MAGICC

---

pymagicc/api.py
tests/test_api.py
tests/test_config.py

The current failure mode if MAGICC6/MAGICC7 is misconfigured is very opaque. It raises an exception when a call to `os.path.exist` gets a `None`. 
This adds an explicit check when `create_copy` is called and raises a sane exception. 2 lines of code change 80 lines of tests!

Exception on missing executable

---

pymagicc/__init__.py

Simple fix for #89
_magiccbinary appears to be unused.

Remove `_magiccbinary` variable

---

.travis.yml
Makefile
appveyor.yml

Makes reasons tests are skipped and expected to fail clearer, useful for debugging CI e.g. output goes from
```sh
$ pytest
============================= test session starts ==============================
platform darwin -- Python 3.6.5, pytest-3.8.0, py-1.6.0, pluggy-0.7.1
rootdir: /Users/zebedeenicholls/Documents/AGCEC/MCastle/pymagicc, inifile: setup.cfg
plugins: cov-2.6.0, nbval-0.9.1
collected 212 items                                                            
tests/test_api.py ......sssss..............                              [ 11%]
tests/test_config.py .....                                               [ 14%]
tests/test_io.py .....................x................................. [ 40%] …
```

Make CI more verbose

---

CHANGELOG.md
Makefile
docsrc/changelog.md
docsrc/developing.md
mkdocs.yml

Pinging @znicholls 
What else should we add here, more details on development/contributing probably?
As discussed in #129 and #116.

Extend docs

---

pymagicc/api.py
tests/test_api.py

Adds the `update_config` and `set_output_variables` functions to `MAGICCBase`. This isn't a fully automatic solution, but rather more of a helper routine. Determining the outputs to turn on from a variable name might be a bit flaky. 
#113

Minimise output

---

Makefile
scripts/test_install.py

```
```
Just makes sure that when we import pymagicc, we go through and import all the dependencies in submodules too to double check that all the dependencies are importable (i.e. installed correctly)

Make test-pypi-install also test imports of all dependencies

---

setup.py

Turns out I'm an idiot, this url business isn't needed, see https://github.com/thedataincubator/expectexception/issues/1
```
```

Fix expectexception install

---

MANIFEST.in

Fairly straightforward. Interesting though that it ignores the trailing / under linux, but not windows

remove trailing / in MANIFEST which is invalid syntax

---

CHANGELOG.rst
pymagicc/definitions/__init__.py
tests/test_definitions.py
tests/test_io.py

```
```
This changes the way permafrost emissions are named. Putting them under emissions is problematic as emissions are implicitly anthropogenic. If you have "Emissions|CO2|Permafrost" then when you add up all sub-categories of CO2 you end up with non-anthropogenic emissions in there too which isn't what you want. This renaming should avoid that sort of thing happening and allows Emissions to remain being implicitly anthropogenic (unfortunately we shouldn't make it explicit as then …

Tweak permafrost read

---

CHANGELOG.rst
pymagicc/core.py
tests/test_core.py

231 no variables read

---

CHANGELOG.rst
pymagicc/core.py
tests/test_core.py

The MAGCFG_USER.CFG file in the magicc repository is in a constant state of flux. It would be nice to overwrite the MAGICC7 config in pymagicc rather than duplicating this everywhere

Override magicc7 user config with sane defaults

---

CHANGELOG.rst
pymagicc/core.py
tests/test_core.py

Doesn't convert out_dynamic_vars to an integer

Allow out_dynamic_vars parameter to be used

---

CHANGELOG.rst
pymagicc/core.py
tests/test_core.py

Switch to using a whitelist for out_ flags

---

CHANGELOG.rst
docs/magicc_flags.rst
tests/test_core.py

For MAGICC7 onwards warn use of multiple emisscen files using a DeprecationWarning. This provides a path to raising an exception in future
Implements 1. in #237

Allow multiple emisscen

---

CHANGELOG.rst
pymagicc/io/mag.py
tests/test_io.py

Add link to AR6 region acronym definitions

---

CHANGELOG.rst
pymagicc/core.py
tests/test_core.py

Check for conflict clashes

---

CITATION.cff

With GitHub adding support for CITATION.cff files to display a citation info on the side (see e.g. https://github.com/IAMconsortium/pyam/) i though it might be worth adding one here too.
https://twitter.com/natfriedman/status/1420122675813441540
With Zenodo also using this for displaying info on their website when dong releases i'm not sure how all of this will render out.
https://twitter.com/zotero/status/1420515377390530560
I've copied the citation info from the Readme and added a link to the 'latest' DOI from Zenodo.
We also ought to create releases to trigger a Zenodo archival, not sure if some beta versions should also be archived as they might have been used in papers?
Full spec: https://github.com/citation-file-format/citation-file-format

Add citation cff file

---

CHANGELOG.rst
pymagicc/core.py

Make level check stricter

---

CITATION.cff

Reformat using online tool
