pymagicc/api.py
Copies all files (excluding subdirectories) in run and bin folders. Bin folder currently doesn't exist in any distribution, but could in the near future. All files in the root of the MAGICC distribution are also copied
Fixes #43
=> Explicitly copy run directory

Makefile
@rgieseke can you check this and maybe add to CI please?
=> Update Makefile with test target

README.md, pymagicc/api.py, pymagicc/config.py, tests/test_api.py, tests/test_config.py
Fixes #61 and add some additional documentation
=> Replace MAGICC_EXECUTABLE env var with MAGICC_EXECUTABLE_6

pymagicc/api.py, tests/test_api.py
=> Raise FileNotFoundError when specified root_dir is not found

Makefile, README.md, pymagicc/__init__.py, pymagicc/api.py, pymagicc/config.py, pymagicc/input.py, setup.py, tests/conftest.py, tests/test_api.py, tests/test_config.py, tests/test_input.py, tests/test_pymagicc.py
Adds an autoformat task and unifies coding style using the **Black** formatter.
@znicholls @lewisjared Any open PRs should be able to be mergeable after a rebase and `make black`.
=> Autoformat in black

tests/test_api.py
Very brief, just adding tcr/ecs diagnosis tests into master
=> Few things I noticed

CHANGELOG.md
=> Prep for v1.3.2

pymagicc/api.py, pymagicc/input.py, setup.cfg
=> Fix flake8 warnings

README.md
Adds instructions for how to use the pull request templates to the repo.
Please add a single line in the changelog notes similar to the following:
```
- (#XX)[http://link-to-pr.com] Added feature which does something
```
=> Add instructions for PRs

.gitignore
and add some more comments ...
=> Move custom gitignore stuff to top

README.rst
=> Use `make test` instead of non-existing script

setup.py
=> Fix Readme formatting for PyPI

README.rst
=> Add citation recommendation for Pymagicc

docs/pymagicc.api.rst, pymagicc/api.py
=> Put replacement in docs rather than docstring

MANIFEST.in
=> Update MANIFEST to fix broken package

CHANGELOG.rst, tests/test_api.py, tests/test_io.py
=> 124 Update missing MAGICC binary in tests

CHANGELOG.rst, docs/development.rst
=> Make release process as automatic as possible

Dockerfile, docs/development.rst
Closes #138 
Further automation can be done later, but at least it's now mentioned in the docs.
=> Check binder after release

CHANGELOG.rst, docs/index.rst, docs/magicc_variables.rst
=> Add MAGICC variable handy reference

CHANGELOG.rst, pymagicc/core.py, tests/test_core.py
```
```
Update the passing of config to and from MAGICC. The new tests identify previous bugs (and ensure they don't come back).
=> Config bugs

.travis.yml
=> Update Linux version for Travis

CHANGELOG.rst, pymagicc/core.py, pymagicc/io.py, tests/test_core.py, tests/test_io.py
=> 203 scen column length

pymagicc/io.py, setup.py, tests/test_io.py
=> Adjust to make sure openscm can import pymagicc

CHANGELOG.rst, pymagicc/io.py, setup.py, tests/test_io.py
=> Move to new openscm naming

setup.py
It seems there is no real consensus (https://stackoverflow.com/questions/9999829/how-to-specify-multiple-authors-emails-in-setup-py) but it's more of a hint (and not necessarily machine readable)...
=> Add @znicholls as author in setup.py

setup.py
Hotfix for an issue I'm having
=> Add decoder to README read

tests/test_io.py
I think this makes it slightly more obvious what is going on?
=> Clean up test

CHANGELOG.rst, pymagicc/io.py
I wasn't able to produce a simple test to reproduce the output seen when running scmcallib, but I think that this resolves the error message. Anyway it is better practise to use a context manager with open file handles
=> Ensure input file is closed

CHANGELOG.rst, pymagicc/core.py, tests/test_core.py
=> Prioritise binout over out files

CHANGELOG.rst, pymagicc/definitions/__init__.py, tests/test_definitions.py, tests/test_io.py
=> Fix permafrost read in

CHANGELOG.rst, setup.py
=> Remove pyam url dependency

CHANGELOG.rst, pymagicc/__init__.py, pymagicc/core.py, pymagicc/io.py, setup.py, tests/test_core.py
```
```
@rgieseke if you checkout the pymagicc-2-0-running branch of magicc and do `export MAGICC_EXECUTABLE_7=path/to/magicc/bin/magicc` then do `make test` all the tests should pass...
=> MAGICC7 updates

CHANGELOG.rst, pymagicc/core.py, setup.py, tests/test_core.py
=> Enable access to magicc's stderr

CHANGELOG.rst, pymagicc/core.py, setup.py, tests/conftest.py, tests/test_core.py
Optional strict parameter to allow runs to continue with invalid configuration
=> Added strict mode for MAGICCBase

CHANGELOG.rst, appveyor.yml
Attempt to hotfix appveyor so #264 can continue
=> Hotfix appveyor

docs/magicc_flags.rst
=> Tweak magicc_flags.rst

notebooks/Building-Scenarios.ipynb, notebooks/Run-Modes.ipynb
=> Remove false failures in notebooks

CHANGELOG.rst, notebooks/Building-Scenarios.ipynb, notebooks/io-Examples.ipynb, pymagicc/__init__.py, pymagicc/core.py, setup.py, tests/test_core.py, tests/test_pymagicc.py
=> Fix requirements, make errors clearer and add more control for MAGICC7 users

CHANGELOG.rst, Makefile
```
```
@rgieseke same deal as https://github.com/rgieseke/pandas-datapackage-reader/pull/9
=> Add sdist to release

CHANGELOG.rst, notebooks/Diagnose-TCR-ECS-TCRE.ipynb, pymagicc/core.py, setup.py, tests/test_core.py
```
```
Depends on #284 and https://github.com/lewisjared/scmdata/pull/28
=> Use pint when diagnosing ECS, TCR and TCRE values

CHANGELOG.rst, pymagicc/io.py, tests/test_io.py
=> Update SCEN7 writer to handle single variable writing

CHANGELOG.rst, docs/conf.py
=> Update name in docs

CHANGELOG.rst, pymagicc/definitions/__init__.py, pymagicc/io.py, tests/test_data/expected_files/EXPECTED_CO2_EMIS.IN, tests/test_data/expected_files/EXPECTED_HISTRCP85_SOLAR_RF.IN, tests/test_data/expected_files/EXPECTED_HISTRCP_NOXI_EMIS.IN, tests/test_data/expected_files/EXPECTED_HISTSSP_CO2I_EMIS.IN, tests/test_io.py
=> Undo fortran cases

CHANGELOG.rst, pymagicc/definitions/__init__.py, tests/test_definitions.py
=> Aerosol ground heat variables

CHANGELOG.rst, pymagicc/core.py
=> Copy ``run`` recursively

.github/workflows/ci-cd-workflow.yml, Makefile, setup.py
I think the install failures are a pip issue not our scmdata packaging...
=> Unpin pandas and use new pip features

CHANGELOG.rst, pymagicc/definitions/__init__.py, setup.py, tests/test_definitions.py
=> Ar6regions

.github/workflows/ci-cd-workflow.yml, pymagicc/io/scen.py, tests/test_io.py
=> Format and run CI

CHANGELOG.rst, pymagicc/io/compact.py, tests/test_io.py, tests/test_pymagicc.py
=> Fix up tests

README.rst
=> Fix Readme

.github/workflows/ci-cd-workflow.yml
=> Hot fix deploy

CHANGELOG.rst, pymagicc/io/base.py
=> Switch to using sep instead of delim_whitespace
